# Generated by Django 5.2.3 on 2025-06-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_bookinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
