# Generated by Django 5.2.3 on 2025-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='movies/'),
            preserve_default=False,
        ),
    ]
